### PR TITLE
Dev dwelling_owner

### PR DESCRIPTION
**Pull request by Arruza17**
Owner view done, started making the testFx but not finished yet

### CODE REVIEW

**Review by jorgeccst — APPROVED** [review]
Lots of text.

**Comment by Arruza17** [comment]
> Lots of text.

Thanks for watching every SINGLE one of the files! :)

**Review by yeraysampedro — APPROVED** [review]
I dont know why the heck did I even spend time reading this...

**Comment by Arruza17** [comment]
> I dont know why the heck did I even spend time reading this...

You don't believe it yourself.

**Pull request closed without merging**
