### PR TITLE
Dev user rest

### PR DESCRIPTION
**Pull request by yeraysampedro**
All the views for user_rest working

### CODE REVIEW

**Review by Arruza17 — APPROVED** [review]
Able to merge! Lets go

**Review by jorgeccst — APPROVED** [review]
Everything ok, ready to merge!

**Comment by yeraysampedro** [comment]
> download
Do you think you are el guasón?
image

**Review by AdrianPerez09 — APPROVED** [review]
Everything looks fine. Ready to merge

**Pull request merged**
